# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170724_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '\u0406\u0441\u043f\u0438\u0442', 'verbose_name_plural': '\u0406\u0441\u043f\u0438\u0442\u0438'},
        ),
    ]
