# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20170724_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exams_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Group', verbose_name='\u0413\u0440\u0443\u043f\u0430'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='teacher_name',
            field=models.CharField(max_length=256, verbose_name='\u041f\u0406\u0411 \u0432\u0438\u043a\u043b\u0430\u0434\u0430\u0447\u0430'),
        ),
    ]
