# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_result_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_exam',
            name='hps',
            field=models.CharField(max_length=256, null=True, verbose_name='\u041e\u0446\u0456\u043d\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='result_exam',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442'),
        ),
        migrations.AlterField(
            model_name='result_exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Exam', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442'),
        ),
    ]
