# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170726_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='students_group',
            new_name='student_group',
        ),
    ]
